=== UO301188/sew/MotoGP-Desktop/xml/circuito.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
	targetNamespace="http://www.uniovi.es"
	xmlns="http://www.uniovi.es"
	elementFormDefault="qualified">
	<xs:element name="circuito">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="nombre" />
				<xs:element ref="longitud" />
				<xs:element ref="anchura" />
				<xs:element ref="fecha" />
				<xs:element ref="hora" />
				<xs:element ref="numVueltas" />
				<xs:element ref="localidad" />
				<xs:element ref="pais" />
				<xs:element ref="patrocinador" />
				<xs:element ref="referencias" />
				<xs:element ref="galeriaFotos" />
				<xs:element ref="galeriaVideos" />
				<xs:element ref="origen" />
				<xs:element ref="tramos" />
				<xs:element ref="vencedor" />
				<xs:element ref="clasificacion" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="nombre" type="xs:string" />
	<xs:element name="longitud">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="xs:decimal">
					<xs:attribute name="unidad" type="xs:string" use="required" fixed = "m"/>
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>

	<xs:element name="anchura">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="xs:decimal">
					<xs:attribute name="unidad" type="xs:string" use="required" fixed = "m"/>
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>
	<xs:element name="fecha">
        <xs:simpleType>
            <xs:restriction base="xs:date">
                <xs:minInclusive value="2025-01-01"/>
                <xs:maxInclusive value="2025-12-31"/>
            </xs:restriction>
        </xs:simpleType>
    </xs:element>

	<xs:element name="hora">
        <xs:complexType>
            <xs:simpleContent>
                <xs:extension base="xs:time">
                    <xs:attribute name="zona" type="xs:string" use="optional" default="+01:00"/>
                </xs:extension>
            </xs:simpleContent>
        </xs:complexType>
    </xs:element>

	<xs:element name="numVueltas">
        <xs:simpleType>
            <xs:restriction base="xs:positiveInteger">
                <xs:minInclusive value="1"/>
                <xs:maxInclusive value="500"/>
            </xs:restriction>
        </xs:simpleType>
    </xs:element>

	<xs:element name="localidad" type="xs:string" />
	<xs:element name="pais" type="xs:string" />
	<xs:element name="patrocinador" type="xs:string" />
	
	<xs:element name="referencias">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="referencia" minOccurs="3" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="titulo" type="xs:string"/>
                            <xs:element name="autor" type="xs:string" minOccurs="0"/>
                            <xs:element name="aÃ±o" type="xs:gYear" minOccurs="0"/>
                        </xs:sequence>
                        <xs:attribute name="url" type="xs:anyURI" use="optional"/>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>



	<xs:element name="galeriaFotos">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="foto" minOccurs="1" maxOccurs="5">
                    <xs:complexType mixed="false">
                        <xs:attribute name="src" type="xs:string" use="required"/>
                        <xs:attribute name="alt" type="xs:string" use="required"/>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

	<xs:element name="galeriaVideos">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="video" minOccurs="1" maxOccurs="3">
                    <xs:complexType mixed="false">
                        <xs:attribute name="src" type="xs:string" use="required"/>
                        <xs:attribute name="alt" type="xs:string" use="required"/>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

	<xs:element name="origen">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="longitudCoord">
                    <xs:complexType>
                        <xs:simpleContent>
                            <xs:extension base="xs:decimal">
                                <xs:attribute name="unidad" type="xs:string" use="required" fixed="deg"/>
                            </xs:extension>
                        </xs:simpleContent>
                    </xs:complexType>
                </xs:element>
                <xs:element name="latitudCoord">
                    <xs:complexType>
                        <xs:simpleContent>
                            <xs:extension base="xs:decimal">
                                <xs:attribute name="unidad" type="xs:string" use="required" fixed="deg"/>
                            </xs:extension>
                        </xs:simpleContent>
                    </xs:complexType>
                </xs:element>
                <xs:element name="altitudCoord">
                    <xs:complexType>
                        <xs:simpleContent>
                            <xs:extension base="xs:decimal">
                                <xs:attribute name="unidad" type="xs:string" use="required" fixed="m"/>
                            </xs:extension>
                        </xs:simpleContent>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

	<xs:element name="tramos">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="tramo" minOccurs="1" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="puntoFinal">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="longFinal">
                                            <xs:complexType>
                                                <xs:simpleContent>
                                                    <xs:extension base="xs:decimal">
                                                        <xs:attribute name="unidad" type="xs:string" use="required" fixed="deg"/>
                                                    </xs:extension>
                                                </xs:simpleContent>
                                            </xs:complexType>
                                        </xs:element>
                                        <xs:element name="latFinal">
                                            <xs:complexType>
                                                <xs:simpleContent>
                                                    <xs:extension base="xs:decimal">
                                                        <xs:attribute name="unidad" type="xs:string" use="required" fixed="deg"/>
                                                    </xs:extension>
                                                </xs:simpleContent>
                                            </xs:complexType>
                                        </xs:element>
                                        <xs:element name="altFinal">
                                            <xs:complexType>
                                                <xs:simpleContent>
                                                    <xs:extension base="xs:decimal">
                                                        <xs:attribute name="unidad" type="xs:string" use="required" fixed="m"/>
                                                    </xs:extension>
                                                </xs:simpleContent>
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="sector" type="xs:positiveInteger"/>
                        </xs:sequence>
                        <xs:attribute name="distancia" use="required">
                            <xs:simpleType>
                                <xs:restriction base="xs:decimal">
                                    <xs:minInclusive value="0.1"/>
                                </xs:restriction>
                            </xs:simpleType>
                        </xs:attribute>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

	<xs:element name="vencedor">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="nombreVencedor" type="xs:string"/>
                <xs:element name="duracion" type="xs:duration"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
	
	<xs:element name="clasificacion">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="puesto" minOccurs="3" maxOccurs="3">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="piloto" type="xs:string"/>
                            <xs:element name="puntos" type="xs:nonNegativeInteger"/>
                        </xs:sequence>
                        <xs:attribute name="pos" type="xs:positiveInteger" use="required"/>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

</xs:schema>

=== UO301188/sew/MotoGP-Desktop/xml/circuitoEsquema.xml
<?xml version="1.0" encoding="UTF-8"?>
<circuito xmlns="http://www.uniovi.es"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.uniovi.es circuito.xsd">

	<nombre>Circuito Internazionale del Mugello</nombre>

	<longitud unidad="m">5243.0</longitud>
	<anchura unidad="m">14.0</anchura>

	<fecha>2025-05-11</fecha>
	<hora>14:00:00</hora>

	<numVueltas>23</numVueltas>

	<localidad>Scarperia e San Piero</localidad>
	<pais>Italia</pais>

	<patrocinador>Ducati</patrocinador>

	<referencias>
		<referencia url="https://www.motogp.com/en/circuit/Mugello">
			<titulo>MotoGP Official - Mugello circuit information</titulo>
			<autor>MotoGP</autor>
			<año>2024</año>
		</referencia>
		<referencia url="https://es.wikipedia.org/wiki/Autodromo_Internazionale_del_Mugello">
			<titulo>Wikipedia - Autodromo Internazionale del Mugello</titulo>
			<autor>Wikipedia</autor>
			<año>2025</año>
		</referencia>
		<referencia url="https://www.fim-moto.com">
			<titulo>FIM - Circuit technical data and map</titulo>
			<autor>FIM</autor>
			<año>2023</año>
		</referencia>
	</referencias>

	<galeriaFotos>
		<foto src="../multimedia/Panorama.jpg" alt="Foto panorámica del circuito"/>
		<foto src="../multimedia/RectaMeta.jpg" alt="Foto de la recta de meta del circuito"/>
		<foto src="../multimedia/CurvaSanDonato.jpg" alt="Foto de la curva San Donato del circuito"/>
	</galeriaFotos>

	<galeriaVideos>
		<video src="../multimedia/ResumenCircuito.mp4" alt="Video del resumen del circuito"/>
	</galeriaVideos>

	<origen>
		<longitudCoord unidad="deg">11.3497</longitudCoord>
		<latitudCoord unidad="deg">43.9972</latitudCoord>
		<altitudCoord unidad="m">210.0</altitudCoord>
	</origen>

	<tramos>
		<tramo distancia="650.0">
			<puntoFinal>
				<longFinal unidad="deg">11.3521</longFinal>
				<latFinal unidad="deg">43.9980</latFinal>
				<altFinal unidad="m">212.0</altFinal>
			</puntoFinal>
			<sector>1</sector>
		</tramo>

		<tramo distancia="840.0">
			<puntoFinal>
				<longFinal unidad="deg">11.3540</longFinal>
				<latFinal unidad="deg">44.0002</latFinal>
				<altFinal unidad="m">218.0</altFinal>
			</puntoFinal>
			<sector>1</sector>
		</tramo>

		<tramo distancia="1200.0">
			<puntoFinal>
				<longFinal unidad="deg">11.3458</longFinal>
				<latFinal unidad="deg">44.0010</latFinal>
				<altFinal unidad="m">205.0</altFinal>
			</puntoFinal>
			<sector>2</sector>
		</tramo>

		<tramo distancia="1553.0">
			<puntoFinal>
				<longFinal unidad="deg">11.3497</longFinal>
				<latFinal unidad="deg">43.9972</latFinal>
				<altFinal unidad="m">210.0</altFinal>
			</puntoFinal>
			<sector>3</sector>
		</tramo>
	</tramos>

	<vencedor>
		<nombreVencedor>Marc Marquez</nombreVencedor>
		<duracion>PT41M9.214S</duracion>
	</vencedor>

	<clasificacion>
		<puesto pos="1">
			<piloto>Marc Marquez</piloto>
			<puntos>25</puntos>
		</puesto>
		<puesto pos="2">
			<piloto>Alex Marquez</piloto>
			<puntos>20</puntos>
		</puesto>
		<puesto pos="3">
			<piloto>Francesco Bagnaia</piloto>
			<puntos>16</puntos>
		</puesto>
	</clasificacion>

</circuito>
